### PR TITLE
Fix/vs2017 constexpr constructor not initializing member/jrmwng

### PR DESCRIPTION
**Pull request by jrmwng**

### CODE REVIEW

**Comment by rsdubtso** [comment]
Thanks for the PR. Not sure I understand how to reproduce this. Would inline initialization work too? If yes, I would prefer that instead of a template constructor.

**Comment by jrmwng** [comment]
I pushed a new commit: use "non-static data member initializer" instead of "template constructor"

**Comment by rsdubtso** [comment]
Thanks! I'm very curious how you were able to find this issue -- I could not trigger the error on our side. Otherwise, the changes make sense to me.

**Comment by jrmwng** [comment]
I build via "CMake Targets View" of Visual Studio 2017 with the following error messages (I am not using Intel compiler...)
`  [1/2] C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1415~1.267\bin\HostX64\x64\cl.exe  /nologo /TP -DDNNL_DLL -DDNNL_DLL_EXPORTS -DNOMINMAX -D_WIN -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -IC:\Users\Jeremy\source\repos\mkl-dnn\include -Iinclude -IC:\Users\Jeremy\source\repos\mkl-dnn\src -IC:\Users\Jeremy\source\repos\mkl-dnn\src\common -IC:\Users\Jeremy\source\repos\mkl-dnn\src\cpu -IC:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\xbyak /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MP    /wd4800 /wd4068 /wd4305 /wd4551 /wd4244  /MDd /Zi /Ob0 /Od /RTC1   /Qpar /openmp /showIncludes /Fosrc\cpu\CMakeFiles\dnnl_cpu.dir\cpu_concat.cpp.obj /Fdsrc\cpu\CMakeFiles\dnnl_cpu.dir\ /FS -c C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\cpu_concat.cpp
  FAILED: src/cpu/CMakeFiles/dnnl_cpu.dir/cpu_concat.cpp.obj 
  C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1415~1.267\bin\HostX64\x64\cl.exe  /nologo /TP -DDNNL_DLL -DDNNL_DLL_EXPORTS -DNOMINMAX -D_WIN -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -IC:\Users\Jeremy\source\repos\mkl-dnn\include -Iinclude -IC:\Users\Jeremy\source\repos\mkl-dnn\src -IC:\Users\Jeremy\source\repos\mkl-dnn\src\common -IC:\Users\Jeremy\source\repos\mkl-dnn\src\cpu -IC:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\xbyak /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MP    /wd4800 /wd4068 /wd4305 /wd4551 /wd4244  /MDd /Zi /Ob0 /Od /RTC1   /Qpar /openmp /showIncludes /Fosrc\cpu\CMakeFiles\dnnl_cpu.dir\cpu_concat.cpp.obj /Fdsrc\cpu\CMakeFiles\dnnl_cpu.dir\ /FS -c C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\cpu_concat.cpp
C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\simple_concat.hpp(32): error C3615: constexpr function 'dnnl::impl::cpu::simple_concat_t<dnnl_bf16>::pd_t::pd_t' cannot result in a constant expression
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: failure was caused by 'constexpr' constructor not initializing member 'dnnl::impl::cpu::simple_concat_t<dnnl_bf16>::pd_t::blocks_'
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: This diagnostic occurred in the compiler generated function 'dnnl::impl::cpu::simple_concat_t<dnnl_bf16>::pd_t::pd_t(dnnl::impl::engine_t *,const dnnl::impl::primitive_attr_t *,const dnnl::impl::memory_desc_t *,int,int,const dnnl::impl::memory_desc_t *)'
C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\simple_concat.hpp(32): error C3615: constexpr function 'dnnl::impl::cpu::simple_concat_t<dnnl_s32>::pd_t::pd_t' cannot result in a constant expression
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: failure was caused by 'constexpr' constructor not initializing member 'dnnl::impl::cpu::simple_concat_t<dnnl_s32>::pd_t::blocks_'
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: This diagnostic occurred in the compiler generated function 'dnnl::impl::cpu::simple_concat_t<dnnl_s32>::pd_t::pd_t(dnnl::impl::engine_t *,const dnnl::impl::primitive_attr_t *,const dnnl::impl::memory_desc_t *,int,int,const dnnl::impl::memory_desc_t *)'
C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\simple_concat.hpp(32): error C3615: constexpr function 'dnnl::impl::cpu::simple_concat_t<dnnl_s8>::pd_t::pd_t' cannot result in a constant expression
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: failure was caused by 'constexpr' constructor not initializing member 'dnnl::impl::cpu::simple_concat_t<dnnl_s8>::pd_t::blocks_'
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: This diagnostic occurred in the compiler generated function 'dnnl::impl::cpu::simple_concat_t<dnnl_s8>::pd_t::pd_t(dnnl::impl::engine_t *,const dnnl::impl::primitive_attr_t *,const dnnl::impl::memory_desc_t *,int,int,const dnnl::impl::memory_desc_t *)'
C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\simple_concat.hpp(32): error C3615: constexpr function 'dnnl::impl::cpu::simple_concat_t<dnnl_u8>::pd_t::pd_t' cannot result in a constant expression
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: failure was caused by 'constexpr' constructor not initializing member 'dnnl::impl::cpu::simple_concat_t<dnnl_u8>::pd_t::blocks_'
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: This diagnostic occurred in the compiler generated function 'dnnl::impl::cpu::simple_concat_t<dnnl_u8>::pd_t::pd_t(dnnl::impl::engine_t *,const dnnl::impl::primitive_attr_t *,const dnnl::impl::memory_desc_t *,int,int,const dnnl::impl::memory_desc_t *)'
C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\simple_concat.hpp(32): error C3615: constexpr function 'dnnl::impl::cpu::simple_concat_t<dnnl_f32>::pd_t::pd_t' cannot result in a constant expression
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: failure was caused by 'constexpr' constructor not initializing member 'dnnl::impl::cpu::simple_concat_t<dnnl_f32>::pd_t::blocks_'
  C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu/simple_concat.hpp(32): note: This diagnostic occurred in the compiler generated function 'dnnl::impl::cpu::simple_concat_t<dnnl_f32>::pd_t::pd_t(dnnl::impl::engine_t *,const dnnl::impl::primitive_attr_t *,const dnnl::impl::memory_desc_t *,int,int,const dnnl::impl::memory_desc_t *)'
  [2/2] C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1415~1.267\bin\HostX64\x64\cl.exe  /nologo /TP -DDNNL_DLL -DDNNL_DLL_EXPORTS -DNOMINMAX -D_WIN -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -IC:\Users\Jeremy\source\repos\mkl-dnn\include -Iinclude -IC:\Users\Jeremy\source\repos\mkl-dnn\src -IC:\Users\Jeremy\source\repos\mkl-dnn\src\common -IC:\Users\Jeremy\source\repos\mkl-dnn\src\cpu -IC:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\xbyak /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MP    /wd4800 /wd4068 /wd4305 /wd4551 /wd4244  /MDd /Zi /Ob0 /Od /RTC1   /Qpar /openmp /showIncludes /Fosrc\cpu\CMakeFiles\dnnl_cpu.dir\simple_concat.cpp.obj /Fdsrc\cpu\CMakeFiles\dnnl_cpu.dir\ /FS -c C:\Users\Jeremy\source\repos\mkl-dnn\src\cpu\simple_concat.cpp
  ninja: build stopped: subcommand failed.
`

**Comment by vpirogov** [comment]
Thank you for your contribution!

**Pull request merged**
