### PR TITLE
Enables OpenMP with MSVC

### PR DESCRIPTION
**Pull request by TechnikEmpire**
These changes enable users to enable OpenMP support when using Microsoft's compiler. The only real issue here is about a 100 or so declarations of `pragma omp simd`. MSVC does auto-vectorization and it is enabled by default, and is disabled or controlled on a per-instance basis with `pragma'`s, so all these declarations will never be supported by MSVC, even if they upgrade OpenMP support, and thus they need to be guarded for that specific compiler.

Performance gains are significant so this needs to be done. When using the existing mkl-dnn code as the back end of `Intel-Caffe`, the default Caffe back end actually out-performs mkl-dnn in my tests (restnet50 forward pass). However, with OpenMP enabled via these changes, it out-performs Caffe's default back end with a ~50% increase in execution speed.

### CODE REVIEW

**Comment by emfomenk** [comment]
Hi @TechnikEmpire,

Conceptually looks good. Really good -- missing openmp in case of MSVS compiler is indeed something we must fix.
Thanks for pointing that out!

I don't like lots of `#ifdefs`... Do you think we can use `_pragma/__Pragma` approach?
I will try few experiments and then come back if find one. Otherwise will have to proceed with `#ifdefs`.

**Comment by TechnikEmpire** [comment]
There's a workaround for 'collapse(x)' for msvc defined to nothing in the thread header I included. I wonder if something similar could be done for the simd but that might get ugly too because there's variations of it.

**Comment by emfomenk** [comment]
Yeah, exactly. We had partial solution for non-supported OpenMP 2.0, this `#define collapse(x)`.

For `pragma omp simd` I though of something like:
```c++
// mkldnn_thread.h -- tentative
#ifdef MSVC
#define PRAGMA_OMP_SIMD(x) // nop
#else

#ifdef _WIN32
#define PRAGMA_OMP_SIMD(x) __Pragma("omp simd" ## #x)
#else
#define PRAGMA_OMP_SIMD(x) _pragma("omp simd" ## #x)
#endif
#endif

// code
PRAGMA_OMP_SIMD(reduction(+:var))
for (int i = 0 .. n) var += x[i];
```

**Comment by TechnikEmpire** [comment]
Yeah I was just doing some reading based on your idea and I like that way better, making a sort of compiler-agnostic simd directive. I'll do make that change a little later on. This can be closed and I'll just reset my fork, apply this and submit a new PR.

**Comment by emfomenk** [comment]
oK, thank you!
If I am able to start doing that work earlier than you (unlikely) I will make a note in this thread.
Looking forward to see the PR :)

**Comment by TechnikEmpire** [comment]
@emfomenk Do I need to be concerned with integer overflow or capacity in areas like `::omp_driver_4d(...)` in `jit_uni_reorder.cpp`? VS2017/msvc 14.x enforces an openmp rule on `parallel` where the index needs to be signed. That means I need to drop the `size_t` declarations to be signed types like an `intptr_t` (long long). I'm wondering if there was any other reason than good coding practice for using `size_t` though, so that I can safely drop the unsigned indices.

**Comment by emfomenk** [comment]
I would suggest using `ptrdiff_t` as a singed analogue of `size_t`.
Ideally it should be `ssize_t` but this type has some portability issues.

You definitely should use the type of the same width, so replacing `size_t` with `long` is not a good idea, cause on Windows 64 `sizeof(size_t) = 8 > sizeof(long) = 4`.

**Comment by TechnikEmpire** [comment]
@emfomenk Ok thanks, will follow your recommendation.

I ended up coming up with the following, because the original macro's didn't work for a few reasons:

```C++
#if defined(_OPENMP)
	#include <omp.h>

	/* VisualStudio still support omp 2.0 */
	#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
		#define collapse(x)

		// nop that doesn't produce warnings.
		// PRAGMA_OMP_SIMD(x) will flood 4003
		// warnings where no arg is supplied
		// beyond omp simd.
		#define PRAGMA_OMP_SIMD(...)
		#define PRAGMA_OMP_SIMD_CLAUSE(...)
	#else
		#define _PRAGMA_OMP_CONCAT(x) _Pragma(#x)
		#define PRAGMA_OMP_SIMD() _Pragma("omp simd")
		#define PRAGMA_OMP_SIMD_CLAUSE(x) _PRAGMA_OMP_CONCAT(omp simd x)
	#endif // defined(_MSC_VER) && !defined(__INTEL_COMPILER)
#else
```
It seems to eval correctly on gcc, works fine without emitting any warnings on msvc and should work on clang as well.

See [here] for gcc dump of source code after preprocessor eval is complete. (http://coliru.stacked-crooked.com/a/92edd64d8f0fab42).

**Comment by TechnikEmpire** [comment]
lol I have to adjust the scope of the else definiton. Doing too much at once today. Anyway you get the idea.

**Comment by emfomenk** [comment]
Looks fine to me. Waiting for PR :)

*Quick comment*
For the PR please remove the indentation before `#`.
According to the standard `#` must be the first symbols of the line.
You might indent define though if you wish.

**Comment by TechnikEmpire** [comment]
@emfomenk I was about to submit PR but now MSVC is randomly being stupid about `threadprivate` directive even though it's fully supported according to documentation. As soon as I figure out what's up there, I'll submit it.

**Pull request closed without merging**
