### PR TITLE
find_package(OpenMP) is not work for llvm in mac 10.13.2, so just for…

### PR DESCRIPTION
**Pull request by liyuming1978**
I am in porting mkl-dnn to paddlepaddle in MAC (10.13.2), since the default clang for Mac is not supported openmp, so I use brew to install llvm.
but I find if I compile mkl-dnn with cmake  -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ .. ,  the speed is too slow.
the reason is find_package(OpenMP) will fail to this setting.
I change the cmake for openmp, and just force to use libiomp5 in Mac of clang.

### CODE REVIEW

**Comment by liyuming1978** [comment]
even flow https://gist.github.com/svenevs/f00ed3898d2af6248921b63254aa8cc1
it doesn't work in my mac

**Comment by rsdubtso** [comment]
Does `cmake -DOpenMP_C_FLAGS=-fopenmp=libiomp5 -DOpenMP_CXX_FLAGS=-fopenmp=libiomp5` work?

**Comment by liyuming1978** [comment]
it partly works! .   must add set(CMAKE_EXE_LINKER_FLAGS "-L${MKLIOMP5LIBPATH} -liomp5"),
if not, make test some test will crash.

**Comment by liyuming1978** [comment]
it can compile with poor performance.  I get another way:
cmake -DCMAKE_C_FLAGS=-fopenmp=libiomp5 -DCMAKE_CXX_FLAGS=-fopenmp=libiomp5 -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ ..

and must add set(CMAKE_EXE_LINKER_FLAGS "-L${MKLIOMP5LIBPATH} -liomp5")
if not add ,  make test some test will crash

**Comment by liyuming1978** [comment]
but anyway,  since here just use libiomp5, not compiler openmp lib,  why use find_package(OpenMP) to get the path?   just check compiler supports openmp or not is enough.

**Comment by liyuming1978** [comment]
since  cmake -DCMAKE_C_FLAGS=-fopenmp=libiomp5 -DCMAKE_CXX_FLAGS=-fopenmp=libiomp5 -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ ..  is working for paddlepaddle link , close pull request.

**Comment by rsdubtso** [comment]
Okay... I was thinking about reworking the patch, but we will just probably mention this trick in the README.md. Thanks!

**Pull request closed without merging**
