### PR TITLE
build: faile gcc5.x build failed, eg: 5.5

### PR DESCRIPTION
**Pull request by haolongzhangm**

### CODE REVIEW

**Comment by haolongzhangm** [comment]
@vpirogov 
i test 5.5 have this issue, 
but do not test gcc6,
test gcc7 and gcc9 support simdlen

**Comment by haolongzhangm** [comment]
@vpirogov
i test 5.5 have this issue,

test gcc6.1,  gcc7 and gcc9 do not have this issue, support simdlen

**Comment by vpirogov** [comment]
Thank you for checking, @haolongzhangm. With that the check should disable simdlen for GCC <= 6.1.

**Comment by rsdubtso** [comment]
> Thank you for checking, @haolongzhangm. With that the check should disable simdlen for GCC <= 6.1.

I think you mean `< 6.1`

**Comment by haolongzhangm** [comment]
@rsdubtso @vpirogov 
I check the gcc release tag, gcc do not have version 6_0
so i think we can  modify the patch as: #if (__GNUC__ <= 5)
pls check

info about gcc release tag:
~/code/gcc$ git tag| grep 6
gcc-3_4_6-release
gcc-4_3_6-release
gcc-4_4_6-release
gcc-4_6_0-release
gcc-4_6_1-release
gcc-4_6_2-release
gcc-4_6_3-release
gcc-4_6_4-release
gcc-6_1_0-release
gcc-6_2_0-release
gcc-6_3_0-release
gcc-6_4_0-release
gcc-6_5_0-release

**Comment by vpirogov** [comment]
This makes sense. One more consideration to be aware of is that CLANG and Intel Compiler define `__GNUC__` macro as well. For example ICC 17.0 that does have OpenMP 4.5 support reports the following:
```
$ icc --version
icc (ICC) 17.0.8 20181031
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
 
$ icc -# hello.c 2>&1 | grep GNUC
    -D__GNUC_GNU_INLINE__ \
    -D__GNUC__=4 \
    -D__GNUC_MINOR__=8 \
    -D__GNUC_PATCHLEVEL__=5 \
```
With that the check you propose will disable simdlen for ICC or CLANG when older GCC is installed in the system, which should not be the case.

**Comment by vpirogov** [comment]
@haolongzhangm,

We discussed this some more with @rsdubtso. To fix the issue properly without introducing degradations the patch should check compiler vendor and version to identify the OpenMP standard supported correctly:

Compiler | OpenMP 4.0 | OpenMP 4.5
-- | -- | --
Intel | >=15.0 | >=17.0
Clang | >= 3.3 | >= 3.9
GCC | >= 4.9 | >= 6.1
MSVS | N/A | N/A

If you would like to work on this please let me know. Otherwise I would ask someone from the team to implement the fix and close this PR.

**Comment by haolongzhangm** [comment]
@vpirogov

OK, pls close this PR, then fix this issue inside u team, ths!

**Comment by vpirogov** [comment]
Thank you for the report and help with the investigation, @haolongzhangm!

**Comment by vpirogov** [comment]
Fix is implemented in a4209e093c5cde10011607a820e2098cef0ae002.

**Pull request closed without merging**
