### PR TITLE
Add some logs to the rnn examples

### PR DESCRIPTION
**Pull request by WilliamTambellini**
The rnn examples are pretty quiet just outputting "ok". That change just logs some variables and the exec time.

### CODE REVIEW

**Comment by emfomenk** [comment]
Looks fine to me.
Few minor comments.

1. It is worth noting that the time would be print for a `warm up` run (i.e. the first run), No one should expect that the time printed really corresponds to the performance of the primitive. In addition, I see we use sequential `memset`, which might lead to further sub-optimal performance. 

2. Maybe we need to add some comments on what these sizes mean or at least say what the example tries to simulate (to give some idea on what these size stand for). Cast @mgouicem for input here.

3. I think there are too many variables printed on the screen. Maybe it better to print them from the new-line each?

**Comment by mgouicem** [comment]
Hi @WilliamTambellini  and thanks for the PR.
Looks good to me too.

Just one quick question: why do you want to print the timings?
Here the main purpose of the example is not to showcase the best performance for the model but how a user can use the RNN API. As mentioned by @emfomenk, the attention is not implemented for best performance but for readability, and furthermore, timing for one run of the topology would not be representative of real usage scenarios, so I do not know how useful it would be. 

If one is interested in the MKL-DNN RNN primitive performance, they can use `benchdnn`, which can output the primitive performance with the `--mode=p` option.

**Comment by WilliamTambellini** [comment]
Hi @emfomenk 
Tks.
Patched : 
1 reformulated to "exec time including warmup"
2 translated raw variable names to the meaning of these vars
3 now prints 1 var per line

**Comment by WilliamTambellini** [comment]
Hi @mgouicem 
Indeed, I have seen these examples are not for performance show purpose and it seems clear these are just examples.
I have just added the timing :
- to check that initialization was not time consuming vs execution 
- to easily see the steady execution time (not relying on the unix time command)
- later to see the effect of some variables on speed (batchsize, feature size...) but it would require to set these variable at runtime meaning refactoring some global static variables so out of scope for that change. 
Anyway I could remove the timer if you d like me to.
kind
W.

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

Let's remove timing to avoid confusion. Other than that -- LGTM. 👍 
I am promoting the enhancement.

**Comment by emfomenk** [comment]
Merged!
Thanks for the contribution! :tada:

**Pull request merged**
