### PR TITLE
VANILLA cpu dispatch and cross-compilation basics

### PR DESCRIPTION
**Pull request by kruus**
# Description

These patches mainly address adding a basic framework for cross-compilation.  A nice side-benefit is to support runtime CPU dispatch to vanilla implementations, with most layers able to avoid 'unimplemented' or 'skipped'.  Many layers were modified so as to disentangle the optional (but default) jit features from the pure C/C++ component.

- Support cpu dispatch to DNNL_MAX_CPU_ISA=VANILLA, to run only reference (or ref gemm) impls.
- Basic infrastructure for cmake toolchain builds to support cross-compilation of VANILLA to non-x86 systems.  This adjusts a few layers to removes entanglements between jit and non-jit code.
- The default build for any DNNL_CPU (or CMAKE_SYSTEM_PROCESSOR) is DNNL_ISA=FULL.
- A VANILLA build indicates what ISAs can be removed by `cmake -DDNNL_ISA=VANILLA.`
- The VANILLA build becomes close to cross-platform by removing xbyak and jit source files from the library. This provides an entry point for supporting the DNNL API on non-x86 chipsets.  Since DNNL comes with a decent reference gemm, a cross-compiled VANILLA libdnnl.so runs through tests fairly quickly.
- You will still need to provide a cmake/mycpu.cmake toolchain, make other cmake adjustments for cross-compiler flags. Then (barring compiler bugs) all examples and gtests should at least run (\*\*)

Fixes # (634) enhancement, closed, not-a-bug
- reducer ref impl is always made available for non-x86-jit builds (SIMPLE_IMPL automatically set)
- Also master was missing a refresh of `generate_mkldnn_debug.py` about a week ago.
- Some doc/ mkldnn:: broken links were changed to dnnl::

# Checklist

## All Submissions

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`)
      pass locally?
  - examples, gtests, and benchdnn tested for FULL and VANILLA, examples and gtests look OK running CPU dispatch to VANILLA
- [X] Have you formatted the code using clang-format? 
  - Well, a few days ago.
- [ ] DNNL_CPU_EXTERNAL_GEMM=MKL was not tested.  Please review and test. (old cmake parms ought to still work)
  - I did try out DNNL_CPU_EXTERNAL_GEMM=CBLAS

## New features

- [ ] Have you added relevant tests?
  - test_isa_* were modified.
  - Perhaps a cpu-dispatch-to-vanilla can verify that a few info strings no longer contain a "jit" substring?
- [X] Have you provided motivation for adding a new feature?
Here it is:  libdnnl is a very-well thought out API.  Wouldn't it be great to cross-compile it for non-x86 CPUs?  Especially now that it comes with a reference gemm implementation that is quite decent -- in certain cases im2col-gemm using dnnl reference gemm even beat "hand-coded intrinsics" direct convolutions on my non-x86 systems, for example.
- Oh. to automate running 'make test_benchdnn_FOO' for performance (e.g.), you can now pass some BENCHDNN_ARGS from the environment (see `tests/benchdnn/CMakeLists.txt`)
- Oh, I got confused too often between "all" and "any" (flip-flopping several times). Since "vanilla", "any" and "all" are now OK for any target CPU, the "all" was changed to "full" (docs adjusted).
  - is the dispatch doc change to "FULL" ok? My justification is that having both ANY and ALL led to confusion.

## Bug fixes

- [ ] Have you added relevant regression tests?
   - Existing regression tests are fine.
- [ ] Have you included information on how to reproduce the issue (either in a 
      github issue or in this PR)?
      
(\*\*) Some new features are **not** in this patch -- it is already quite large:

- Did **not include** a DNNL_ENABLE_BFLOAT16=0 to remove bfloat16 from VANILLA/non-x86 builds
  - removing bfloat16 support "makes sense" for VANILLA build, but touched 79 files :(
- DNNL_VERBOSE=EXTRA comments don't exactly match the code, because I removed the ugly and long "create" wrapper that reports about skipped or unimplemented impls.  I thought it good to first consider whether the new INSTANCE[_ISA] macros are acceptable.
- For now DNNL_ENABLE_RNN=0 for VANILLA, because it will need a larger patch -- it looks like the only missing piece is a ref impl is for post-ops, and there are some existing ref post-ops that might be good starting points. DNNL_ENABLE_RNN really should disappear completely.  It is ugly.

## Remarks

- While all tests pass, please try to imagine whether there are some subtleties where jit allows some `init()` feature that is _not_ supported by the reference impl.  If this happens, the `init()` function might differ in ways not covered by existing tests.  (For example, in other branches that remove bfloat16 support from libdnnl (not here) the `init()` functions for sure were impacted).
- Performance improvements are **not** addressed.  On the other hand, dispatch to VANILLA shows a majority of gtest times on par or better than with AVX2 + jit creation times.
  - Obvious pain points easily noticable with CPU dispatch to VANILLA are:
    - ref GEMM a bit slower (expected),
    - many int8 operations are way slower than my default AVX2
    - lrn ref impl loops likely yield vector length 5 for usual case (try changing order)
  - changed `tests/benchdnn/CMakeLists.tx` to allow passing args (like performance mode) to `make test_benchdnn_...` ... but running all of them in performance mode takes a _long_ time.
- `consistency.hpp` I use regularly to find out why `init()` functions declined their invitations.  To not cause slowdown, default verbosity builds use old code "as is". This is ugly, and not maintainable in long term.  I'd like to verify assembly output and find macros that provably have zero impact on default builds.  I suppose this could be a separate PR, or you could ask me to fix it after merge
- I guess I'd like src/cpu/gemm/ to move towards a somewhat-standalone API.  One of the gtests has some copy-paste of function declarations, and missing bool 'capability' functions.  Remove comments after having thought about them for a few seconds.
- git logs ... I might not have been able to convince github to ignore a year or so of irrelevant log entries in my very old fork.

### CODE REVIEW

**Comment by emfomenk** [comment]
Hi @kruus,

Thanks for the PR! It is big, reeeeally big 😱 
There are multiple different changes incorporated in it, including the public API / library behavior. I think we should split the PR in a set of such, where each PR will be dedicated to a particular feature. This way it would be easier to review, provide feedback, and adjust the changes.

After a quick look through I have some high-level comments:
1. As many frameworks (and probably other piece of software) rely on DNNL we want to preserve API and behavior backward compatibility as much as possible. The breaking is only allowed if the previous behavior was buggy.
    - In particular, the build system should not change the existing variable. It could add new, however.
2. The API changes (new functionality, new VERBOSE level, new ISAs, replacing `all` with `full`, etc) should be first explicitly agreed with the team. We use RFC, but given that you already have a code, we could have a discussion in the corresponding PR. However, the PR should be dedicated to this particular change so that the discussion is focused on the topic.
3. The patch contains a lot of debug code, such as commented out code
    ```patch
    + //#warning "DNNL_TARGET_X86_JIT is TRUE"
    ```
   or
    ```patch
    - #include "jit_generator.hpp"
    + //#include "jit_generator.hpp"
    ```
   This should be cleaned up.
4. There should not be any changes to ` tests/mkldnn_compat/*` as this directory exists specifically to test that we don't break backward-compatibility in terms of CMake-building and C/C++ API for those who continue using MKL-DNN (i.e. haven't migrated to DNNL yet).

**Comment by kruus** [comment]
Thanks for comments. I will address these.

**Comment by kruus** [comment]
- Are RFCs submitted as issues?
- OK, I'll remove and submit a bunch of smaller RFCs, since there is absolutely no way for CPU dispatch to VANILLA without some public header changes, and clear definition of the semantics.
- changed back to ALL, VANILLA and ANY throughout.
- removed debug and intermediate caps, simplifying the cmake target options a lot.
- tests/mkldnnn_compat/ has *no* modifications for default build.  The change is cause by trying to commit a smaller PR
  - the VANILLA build cannot support rnn without a larger PR to provide a non-jit rnn impl
  - this affects all tests and examples, which should still "pass", and has no effect on the full build.
- Between tiny-PRs, I don't see a way to avoid temporary ugliness, unfortunately.

BTW, the automated PR testing is fantastic.

**Comment by emfomenk** [comment]
> Are RFCs submitted as issues?

Up to you. It could be an issue with a description of the change, or the PR with the corresponding change (and still some description). The issue might be preferable to not waste time on the implementation if it is not accepted. However, if the code is already there it is absolutely oK to bring the code along with the RFC.

> Between tiny-PRs, I don't see a way to avoid temporary ugliness, unfortunately.

Assuming that all PRs will get in, this is probably okayish. However, if PR A has some ugliness which is fixed in PR B, but PR B is not accepted we would need to fix the ugliness in PR A :)

> BTW, the automated PR testing is fantastic.

Yeah, that is thanks to @sakulish for this nice feature! :)

**Pull request closed without merging**
